### ISSUE TITLE
How to control the generated language?

### ISSUE THREAD

**Issue by brosoul** [agsoto/webgenerator#2]
Is there any way to control the text content of the component to the specified language（I hope it is in English）？
![image](https://user-images.githubusercontent.com/61538439/217238687-1e992fb3-a710-4370-bbb4-6368aaaa8724.png)

**Comment by agsoto** [comment]
Hi, the text content for each component is generated based on a Lorem Ipsum. Given the fact that we're trying to generate radom/probabilistic generation of components, that was useful. However In the future an alternative to random content could it be implemented. How would you think is a good idea to control the generated content?

**Comment by brosoul** [comment]
> 

I think the current random generation scheme is suitable for this project. It can quickly generate a sufficient number of pages. However, whether to consider access to natural language generation to generate some text with specified topics in the future.

**Comment by agsoto** [comment]
You're right! It's a good idea. I'll write it down into the Roadmap, maybe with something like ChatGPT (But man, that thing is so powerful I think It can even generate the code for a better random page itself 😅)
